INSERT INTO GENRES (NAME) SELECT 'Комедия'
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Комедия');

INSERT INTO GENRES (NAME) SELECT 'Драма'
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Драма');

INSERT INTO GENRES (NAME) SELECT 'Мультфильм'
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Мультфильм');

INSERT INTO GENRES (NAME) SELECT 'Триллер'
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Триллер');

INSERT INTO GENRES (NAME) SELECT 'Документальный'
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Документальный');

INSERT INTO GENRES (NAME) SELECT 'Боевик'
WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Боевик');

INSERT INTO MPA_RATING (NAME, DESCRIPTION) SELECT 'G', 'у фильма нет возрастных ограничений'
WHERE NOT EXISTS (SELECT 1 FROM MPA_RATING WHERE NAME = 'G');

INSERT INTO MPA_RATING (NAME, DESCRIPTION) SELECT 'PG', 'детям рекомендуется смотреть фильм с родителями'
WHERE NOT EXISTS (SELECT 1 FROM MPA_RATING WHERE NAME = 'PG');

INSERT INTO MPA_RATING (NAME, DESCRIPTION) SELECT 'PG-13', 'детям до 13 лет просмотр не желателен'
WHERE NOT EXISTS (SELECT 1 FROM MPA_RATING WHERE NAME = 'PG-13');

INSERT INTO MPA_RATING (NAME, DESCRIPTION) SELECT 'R', 'лицам до 17 лет просматривать фильм можно только в присутствии взрослого'
WHERE NOT EXISTS (SELECT 1 FROM MPA_RATING WHERE NAME = 'R');

INSERT INTO MPA_RATING (NAME, DESCRIPTION) SELECT 'NC-17', 'лицам до 18 лет просмотр запрещён'
WHERE NOT EXISTS (SELECT 1 FROM MPA_RATING WHERE NAME = 'NC-17');